config/routes.rb
Sabairean::Application.routes.draw do
  root to: 'pages#home'
  get 'about' => 'pages#about'
  get 'app' => 'pages#app'
  get 'contact' => 'pages#contact'
  post 'contact' => 'pages#notify'

  devise_for :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    render layout: 'marketing'
  end

  def about
    render layout: 'marketing'
  end

  def app
    render layout: 'app'
  end

  def contact
    render layout: 'marketing'
  end

  def notify
    ContactMailer.contact(params[:message], params[:subject], params[:email]).deliver
    render layout: 'marketing'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav.html.haml
.row-
  %nav.navbar{:role=>"navigation"}
    .navbar-header
      %ul.nav.navbar-nav
        %li
          %a{:href=>'/'}Home
        %li.active
          %a{:href=>'#/courses'}Courses
      %ul.navnavbar-nav.navbar-right.pull-right
        %li.language-select.dropdown
          %a.language-toggle{:href=>"#", "data-toggle"=>"dropdown"}
            Language 
            %b.caret
          %ul.dropdown-menu
            %li
              %a{:href=>"#"}ភាសាខ្មែរ
            %li
              %a{:href=>"#"}English
            %li
              %a{:href=>"#"}Français

app/views/layouts/app.haml
!!!
%html{lang: 'en', 'ng-app' => 'sabairean'}
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title{'data-i18n' => "__title__"}
      %meta{:content => content_for?(:description) ? yield(:description) : "Sabairean", :name => "description"}
        = stylesheet_link_tag "app", :media => "all"
        = stylesheet_link_tag "http://netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css", :media => "all"
        = javascript_include_tag "application"
        = javascript_include_tag "http://netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/js/bootstrap.min.js"
        = csrf_meta_tags
        = yield(:head)
  %body
    #container.container
      %br

      = render 'layouts/nav'

      %div{'ng-view' => ''}

app/views/layouts/app.html.haml
!!!
%html{lang: 'en', 'ng-app' => 'sabairean'}
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title{'data-i18n' => "__title__"}
      %meta{:content => content_for?(:description) ? yield(:description) : "Sabairean", :name => "description"}
        = stylesheet_link_tag "http://netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css", :media => "all"
        = stylesheet_link_tag "app", :media => "all"
        = javascript_include_tag "application"
        = javascript_include_tag "http://netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/js/bootstrap.min.js"
        = csrf_meta_tags
        = yield(:head)
  %body
    #container.container
      %br

      = render 'layouts/nav'

      %div{'ng-view' => ''}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Sabairean"
      %meta{:content => content_for?(:description) ? yield(:description) : "Sabairean", :name => "description"}
        = stylesheet_link_tag "pages", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    #container.container
      %header
        = render 'layouts/navigation'
        = render 'layouts/messages'
      #main{:role => "main"}
        = yield
      %footer= render 'layouts/footer'

app/views/layouts/marketing.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Sabairean"
      %meta{:content => content_for?(:description) ? yield(:description) : "Sabairean", :name => "description"}
        = stylesheet_link_tag "http://netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css", :media => "all"
        = stylesheet_link_tag "marketing", :media => "all"
        = javascript_include_tag "application"
        = javascript_include_tag "http://netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/js/bootstrap.min.js"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    #container.container
      %header
        = render 'layouts/marketing/navigation'
        = render 'layouts/marketing/messages'
      #main{:role => "main"}
        = yield
      %footer= render 'layouts/marketing/footer'

app/views/layouts/marketing/_footer.html.haml
.clearfix
.supporter-logo= link_to image_tag('supporters/enspiral.png', :alt=>'Enspiral'), 'http://www.enspiral.com', target: '_blank'
.supporter-logo= link_to image_tag('supporters/instedd.jpg', :alt=>'Instedd'), 'http://www.ilabsoutheastasia.org', target: '_blank'
.supporter-logo= link_to image_tag('supporters/worldeducation_logo.jpg', :alt=>'World Education'), 'http://cambodia.worlded.org', target: '_blank'
.supporter-logo= link_to image_tag('supporters/kape_logo.jpg', :alt=>'Kape'), 'http://www.kapekh.org', target: '_blank'
.pull-right.notes
  This project was created as part of the GFN Chalenge
  = link_to image_tag('gfn.gif', :alt=>'GFN Challenge'), 'http://www.gfnchallenge.org'

app/views/layouts/marketing/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/marketing/_navigation.html.haml
.row
	.pull-right= image_tag 'bug.gif'
	.pull-left= link_to image_tag('logo_corner.jpg'), root_path
.row
	%nav.navbar{:role=>"navigation"}
		%ul.nav.nav-bar
			%li= link_to 'Home', root_path
			%li= link_to 'About', about_path
			/%li= link_to 'Blog'
			%li= link_to 'Contact', contact_path

app/views/pages/_new_home.html.haml
%section
  .row
    .col-xs-12.col-sm-6.col-md-6
      %div
        %img#logo.img-responsive.image{:src=>"/assets/mocks/student.jpg"}


      %div
        %p.lead.description
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum


    .col-xs-12.col-sm-6.col-md-6
      .get-started
        %ol
          %p.pull-left.numbers.text-center 1
          %li
            %strong Setup
            %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt utlabore et dolore magna aliqua.

          %p.pull-left.numbers.text-center 2
          %li
            %strong Builds
            %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
          %p.pull-left.numbers.text-center 3
          %li
            %strong Deploy
            %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

      
      = link_to 'Start', app_path, :class=>'btn btn-primary btn-large start-btn'

app/views/pages/_old_home.html.haml
.pull-right= image_tag 'frontpage.jpg', width: 438
%h1 Welcome to Sabairean
%p
  This learning resource was made for Cambodian youth. Learn to programme mobile devices and computers in the Khmer language.
%p Have fun while you learn. Make your own games, play with your friends, amuse your family and surprise your teacher.

.start_button= link_to image_tag('startbutton.jpg'), app_path

app/views/pages/about.html.haml
#about
  %h1 About Sabairean

  %ul
    %li
      %a{href:'#purpose'} Purpose
    %li
      %a{href:'#history'} History
    %li
      %a{href:'#summary'} Summary

  %h2 Purpose
  %p
    %strong
      There are a wave of smartphones and tablets coming into developing countries and they have the potential for
      massive social impact. We help train local programmers to build web and mobile applications to take advantage of this opportunity.

  %p.purpose
    Our mission: To make world class technical education accessible to everyone, everywhere.

  %p In the last 20 years Mobile phones have had a profound effect in developing countries.

  %blockquote
    "Mobile communications offer major opportunities to advance human and economic development – from providing basic
    access to health information to making cash payments, spurring job creation, and stimulating citizen involvement in democratic processes"
    %br
    \--
    %a{href: 'http://www.worldbank.org/en/news/press-release/2012/07/17/mobile-phone-access-reaches-three-quarters-planets-population'}
      World Bank Vice President for Sustainable Development Rachel Kyte
  %p
    Over the same 20 years, computers have had a big impact in the world on all aspects of our personal and professional
    lives – Business, Media, Politics, Education, Entertainment, Health care etc. However in developing economies this
    potential has yet to be realised as computers have been unaffordable for most people. This is changing as
    %strong billions
    of people who have never had access to computers get low cost android devices.

  %p
    Developing countries are at the beginning of a second information revolution which creates significant opportunities for
    economic and social impact. Unfortunately many countries do not have enough people in a position to take advantage of this opportunity.
    There is a lack of trained programmers who can build apps adapted for local people and the formal education institutions are often
    quite poor quality.

  %p
    Our mission is to help people anywhere in the world gain the skills they need to build mobile and web apps.
    We are an international collective of developers committed to providing programmers everywhere access to free resources and world class education
    in their native language.

  %p
    We are beginning with android programming materials in Khmer but our vision is to help people learn any technology in any language.

  %h2 History

  %p
    In April 2013 a group of entrepreneurs, designers and programmers from New Zealand formed the
    %a{href:'http://gfnchallenge.org/'}GFN Challenge
    and went to Cambodia for a week to volunteer on projects for local charities. One of these projects was
    %a{href:'http://www.gritlearning.com/'}Grit Learning
    who are doing fantastic work getting tablets into schools and using educational apps to revolutionize education.

  %p
    But Grit (and their local partner
    %a{href: 'http://www.kapekh.org/'}KAPE
    ) had a problem - all their educational apps were in english and it was difficult finding local developers who could
    translate existing apps, let alone build new ones. So the idea for Sabairean was formed - maybe we could do something
    to help older students learn how to build mobile apps and they could build help build educational apps for the
    younger ones.

  %p
    Our core idea was to create Khmer learning materials in an e-leaning platform and use informal programming clubs as
    a way students could learn how to build mobile apps.
    Together with a cambodian developer from
    %a{href:'http://instedd.org'}INSTEDD
    we built a prototype and trialled it in two schools. The results were positive enough that two
    %a{href: 'http://www.enspiral.com'} Enspiral
    developers returned to Cambodia in July 2013 to continue working on the project.

  %p
    We switched our focus to tertiary level students who often have some basic programming experience but not enough to
    confidently build their own apps. Students typically have quite good english but it is much easier to learn complex
    concepts in their native language and they have a strong preference for learning materials in Khmer. We are now beginning
    our first trials in August 2013 and the journey continues...

  %h2 What we are doing

  %h3 Localised creative commons learning materials
  %p
    We help experienced programmers and teachers create free programming learning materials which are translated into multiple languages.
    Each course is published on github under the creative commons license and free for anyone to use.

  %h3 Open source e-learning platform
  %p
    Our open source platform aggregates these courses and provides an easy to use portal for students to
    %ul
      %li Work through materials in their own time
      %li Help other people with their learning
      %li Build reputation and connect with other programmers

  %h3 Programming clubs
  %p
    Learning solely online is a good start but nothing beats in person interaction so a big part of Sabairean are the informal
    programming clubs.

  %h3 Commercial opportunities
  %p
    Programming clubs are a great start but to really become a strong programmer you need to find work that nurtures your
    growth. So a big focus for Sabairean is to help programmers find work which
    %strong pays well
    and
    %strong supports their learning.

  %p
    Our hope is that this will lead to strong international partnerships between people and companies who can work together to
    build applications that make a significant impact on human and economic development around the world.

app/views/pages/contact.html.erb
<h1>Contact Us</h1>

<%= form_tag '/contact' do %>
    <div>
        <%= label_tag 'subject' %>
        <%= text_field_tag 'subject' %>
    </div>
    <div>
      <%= label_tag 'Your email' %>
      <%= text_field_tag 'email' %>
    </div>
    <div>
        <%= label_tag 'Message' %>
        <%= text_area_tag 'message', nil, size: "25x10" %>
    </div>
    <%= submit_tag "Submit" %>

<% end %>

app/views/pages/home.html.haml
//= render 'pages/new_home'
= render 'pages/old_home'

app/views/pages/notify.html.erb
<p class='notification'>Thank you for your message, we will be in touch as soon as we can.</p>